version: '3.3'

services:
  postgres:
    image: postgres:13.3
    container_name: "${BOT_CONTAINER_NAME:-crypto_bot_db}"
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "999:5432"
